# Generated by Django 6.0.2 on 2026-03-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Posts",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "title",
                    models.CharField(help_text="Введите заголовок поста", max_length=150, verbose_name="Заголовок"),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True, help_text="Напишите содержимое поста", null=True, verbose_name="Содержимое поста"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="blog/images", verbose_name="Превью поста"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_publishing",
                    models.BooleanField(help_text="Признак публикации", verbose_name="Признак публикации"),
                ),
                (
                    "count_views",
                    models.PositiveIntegerField(
                        help_text="Количество просмотров", verbose_name="Количество просмотров"
                    ),
                ),
            ],
            options={
                "verbose_name": "Пост",
                "verbose_name_plural": "Посты",
                "ordering": ["created_at"],
            },
        ),
    ]
