# Generated by Django 6.0.2 on 2026-03-17 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="is_publishing",
            field=models.BooleanField(default=True, help_text="Признак публикации", verbose_name="Признак публикации"),
        ),
    ]
