# Generated by Django 6.0.2 on 2026-03-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_posts_is_publishing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="count_views",
            field=models.PositiveIntegerField(
                default=0, help_text="Количество просмотров", verbose_name="Количество просмотров"
            ),
        ),
    ]
