# Generated by Django 6.0.2 on 2026-03-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_posts_count_views"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posts",
            name="is_publishing",
            field=models.BooleanField(help_text="Признак публикации", verbose_name="Признак публикации"),
        ),
    ]
