# Generated by Django 6.0.2 on 2026-02-25 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "category_name",
                    models.CharField(
                        help_text="Введите название категории", max_length=150, verbose_name="Наименование категории"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание категории")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["category_name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "product_name",
                    models.CharField(
                        help_text="Введите наименование продукта", max_length=150, verbose_name="Наименование продукта"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True, verbose_name="Описание продукта")),
                (
                    "product_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="catalog/images", verbose_name="Изображение продукта"
                    ),
                ),
                ("price", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="category",
                        to="catalog.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
                "ordering": ["product_name", "category", "price"],
            },
        ),
    ]
