# Generated by Django 6.0.2 on 2026-02-25 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/", verbose_name="Изображение продукта"),
        ),
    ]
