# Generated by Django 6.0.2 on 2026-02-26 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_product_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="catalog",
            name="product_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="catalog/images/", verbose_name="Изображение продукта"
            ),
        ),
    ]
